steps:
  # L1
  - key: "base"
    env:
      "DOCKER_PUSH": "true"
    label: ":docker: build base image"
    branches: "buildkite"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"

  # L2
  - key: "audit-deps"
    label: ":nsp: yarn audit"
    env:
      "DOCKER_PULL_DEPENDS_TARGET": "base"
    branches: "buildkite"
    depends_on: "base"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"

  - key: "prep-deps"
    label: ":parcel: yarn install"
    env:
      "DOCKER_PUSH": "true"
      "DOCKER_PULL_DEPENDS_TARGET": "base"
    branches: "buildkite"
    depends_on: "base"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"

  # L3
  - key: "prep-deps-with-files"
    label: ":parcel: install deps with all files"
    env:
      "DOCKER_PUSH": "true"
      "DOCKER_PULL_DEPENDS_TARGET": "prep-deps"
    branches: "buildkite"
    depends_on: "prep-deps"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"

  - key: "prep-deps-with-prod-files"
    label: ":parcel: install deps with prod files"
    env:
      "DOCKER_PUSH": "true"
      "DOCKER_PULL_DEPENDS_TARGET": "prep-deps"
    branches: "buildkite"
    depends_on: "prep-deps"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"

  - key: "test-lint-lockfile"
    label: ":nsp: lint lockfile"
    env:
      "DOCKER_PULL_DEPENDS_TARGET": "prep-deps"
    branches: "buildkite"
    depends_on: "prep-deps"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"

  # L4
  - key: "prep-deps-browser"
    label: ":parcel: install deps with browsers"
    env:
      "DOCKER_PUSH": "true"
      "DOCKER_PULL_DEPENDS_TARGET": "prep-deps-with-files"
    branches: "buildkite"
    depends_on: "prep-deps-with-files"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"

  - key: "prep-test"
    label: ":parcel: unit prep"
    env:
      "DOCKER_PUSH": "true"
      "DOCKER_PULL_DEPENDS_TARGET": "prep-deps-with-prod-files"
    branches: "buildkite"
    depends_on: "prep-deps-with-prod-files"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"

  - key: "prep-build"
    label: ":parcel: yarn dist"
    env:
      "DOCKER_PUSH": "true"
      "DOCKER_PULL_DEPENDS_TARGET": "prep-deps-with-prod-files"
    branches: "buildkite"
    depends_on: "prep-deps-with-prod-files"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"
    # artifact_paths:
    #   - "builds"

  - key: "prep-build-storybook"
    label: ":storybook: build storybook"
    env:
      "DOCKER_PULL_DEPENDS_TARGET": "prep-deps-with-prod-files"
    branches: "buildkite"
    depends_on: "prep-deps-with-prod-files"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"

  - key: "shellcheck"
    label: ":heavy_check_mark: shellcheck"
    branches: "buildkite"
    depends_on: "prep-deps-with-files"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"

  - key: "test-lint"
    label: ":eslint: lint"
    env:
      "DOCKER_PULL_DEPENDS_TARGET": "prep-deps-with-files"
    branches: "buildkite"
    depends_on: "prep-deps-with-files"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"

  # L5
  - key: "prep-build-test"
    label: ":parcel: build test"
    env:
      "DOCKER_PUSH": "true"
      "DOCKER_PULL_DEPENDS_TARGET": "prep-deps-browser"
    branches: "buildkite"
    depends_on: "prep-deps-browser"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"

  - key: "prep-test-flat"
    label: ":parcel: build test flat"
    env:
      "DOCKER_PUSH": "true"
      "DOCKER_PULL_DEPENDS_TARGET": "prep-deps-browser"
    branches: "buildkite"
    depends_on: "prep-deps-browser"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"

  - key: "test-unit"
    label: ":mocha: unit test"
    env:
      "DOCKER_PULL_DEPENDS_TARGET": "prep-test"
    branches: "buildkite"
    depends_on: "prep-test"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"
    # artifact_paths:
    #   - ".nyc_output"
    #   - "coverage"

  - key: "test-unit-global"
    label: ":mocha: unit test global"
    env:
      "DOCKER_PULL_DEPENDS_TARGET": "prep-test"
    branches: "buildkite"
    depends_on: "prep-test"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"

  - key: "test-mozilla-lint"
    label: ":firefox: mozilla lint"
    env:
      "DOCKER_PULL_DEPENDS_TARGET": "prep-build"
    branches: "buildkite"
    depends_on: "prep-build"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"

  # L6
  - key: "test-flat-chrome"
    label: ":chrome: chrome integration test"
    env:
      "DOCKER_PULL_DEPENDS_TARGET": "prep-test-flat"
    branches: "buildkite"
    depends_on: "prep-test-flat"
    commands:
      - "source .buildkite/scripts/pre"
      - "BUILD_TARGET=test-flat docker-build --build-arg browsers='[\"Chrome\"]'"

  - key: "test-flat-firefox"
    label: ":firefox: firefox integration test"
    env:
      "DOCKER_PULL_DEPENDS_TARGET": "prep-test-flat"
    branches: "buildkite"
    depends_on: "prep-test-flat"
    commands:
      - "source .buildkite/scripts/pre"
      - "BUILD_TARGET=test-flat docker-build --build-arg browsers='[\"FireFox\"]'"

  - key: "e2e-chrome"
    label: ":chrome: chrome e2e test %n"
    env:
      "DOCKER_PULL_DEPENDS_TARGET": "prep-build-test"
    branches: "buildkite"
    depends_on: "prep-build-test"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"
    parallelism: 9
    # artifact_paths:
    #   - "test-artifacts"

  - key: "e2e-firefox"
    label: ":firefox: firefox e2e test %n"
    env:
      "DOCKER_PULL_DEPENDS_TARGET": "prep-build-test"
    branches: "buildkite"
    depends_on: "prep-build-test"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"
    parallelism: 9
    # artifact_paths:
    #   - "test-artifacts"

  - key: "benchmark"
    label: ":chrome: benchmark"
    env:
      "DOCKER_PULL_DEPENDS_TARGET": "prep-build-test"
    branches: "buildkite"
    depends_on: "prep-build-test"
    commands:
      - "source .buildkite/scripts/pre"
      - "docker-build"
    # artifact_paths:
    #   - "test-artifacts"
