steps:
  # L0
  - key: "base"
    label: ":docker: build base image"
    branches: "buildkite"
    command: "BUILD_TARGET=base ./.buildkite/scripts/docker-build"

  - key: "audit-deps"
    label: ":nsp: yarn audit"
    branches: "buildkite"
    depends_on: "base"
    command: "BUILD_TARGET=audit-deps ./.buildkite/scripts/docker-build"

  - key: "prep-deps"
    label: ":parcel: yarn install"
    branches: "buildkite"
    depends_on: "base"
    command: "BUILD_TARGET=prep-deps ./.buildkite/scripts/docker-build"

  - key: "prep-deps-with-prod-files"
    label: ":parcel: install deps with prod files"
    branches: "buildkite"
    depends_on: "prep-deps"
    command: "BUILD_TARGET=prep-deps-with-prod-files ./.buildkite/scripts/docker-build"

  - key: "prep-deps-with-files"
    label: ":parcel: install deps with all files"
    branches: "buildkite"
    depends_on: "prep-deps"
    command: "BUILD_TARGET=prep-deps-with-files ./.buildkite/scripts/docker-build"

  - key: "shellcheck"
    label: ":heavy_check_mark: shellcheck"
    branches: "buildkite"
    depends_on: "prep-deps-with-files"
    command: "BUILD_TARGET=shellcheck ./.buildkite/scripts/docker-build"

  - key: "prep-deps-browser"
    label: ":parcel: install deps with browsers"
    branches: "buildkite"
    depends_on: "prep-deps-with-files"
    command: "BUILD_TARGET=prep-deps-browser ./.buildkite/scripts/docker-build"

  - key: "prep-build-storybook"
    label: ":storybook: build storybook"
    branches: "buildkite"
    depends_on: "prep-deps-with-prod-files"
    commands:
      - "BUILD_TARGET=prep-build-storybook ./.buildkite/scripts/docker-build"

  - key: "prep-build"
    label: ":parcel: yarn dist"
    branches: "buildkite"
    depends_on: "prep-deps-with-prod-files"
    command: "BUILD_TARGET=prep-build ./.buildkite/scripts/docker-build"
    # artifact_paths:
    #   - "builds"


  - key: "test-unit"
    label: ":mocha: unit test"
    branches: "buildkite"
    depends_on: "prep-deps-with-files"
    command: "docker run $(./.buildkite/scripts/target2image prep-deps-with-files) yarn test:unit"
    # artifact_paths:
    #   - ".nyc_output"
    #   - "coverage"


  - key: "test-unit-global"
    label: ":mocha: unit test global"
    branches: "buildkite"
    depends_on: "prep-deps-with-files"
    command: "docker run $(./.buildkite/scripts/target2image prep-deps-with-files) yarn test:unit:global"

  - key: "test-lint"
    label: ":eslint: lint"
    branches: "buildkite"
    depends_on: "prep-deps-with-files"
    command:
      - "docker run $(./.buildkite/scripts/target2image prep-deps-with-files) yarn lint"
      - "docker run $(./.buildkite/scripts/target2image prep-deps-with-files) yarn verify-locales"

  - key: "test-lint-lockfile"
    label: ":nsp: lint lockfile"
    branches: "buildkite"
    depends_on: "prep-deps-with-files"
    command: "docker run $(./.buildkite/scripts/target2image prep-deps-with-files) yarn lint:lockfile"

  - key: "prep-scss"
    label: ":scsslint: build scss"
    branches: "buildkite"
    depends_on: "prep-deps-browser"
    command: "BUILD_TARGET=prep-scss ./.buildkite/scripts/docker-build"

  - key: "prep-build-test"
    label: ":parcel: build test"
    branches: "buildkite"
    depends_on: "prep-deps-browser"
    command: "BUILD_TARGET=prep-build-test ./.buildkite/scripts/docker-build"
  # - wait

  ### Level 3
  - key: "test-flat-chrome"
    env:
      browsers: "'[\"Chrome\"]'"
    label: ":chrome: chrome integration test"
    branches: "buildkite"
    depends_on: "prep-scss"
    command: "docker run $(./.buildkite/scripts/target2image prep-scss) yarn test:flat"

  - key: "test-flat-firefox"
    env:
      browsers: "'[\"FireFox\"]'"
    label: ":firefox: firefox integration test"
    branches: "buildkite"
    depends_on: "prep-scss"
    command: "docker run $(./.buildkite/scripts/target2image prep-scss) yarn test:flat"

  - key: "e2e-chrome"
    label: ":chrome: chrome e2e test %n"
    branches: "buildkite"
    depends_on: "prep-build-test"
    commands:
      - "docker run $(./.buildkite/scripts/target2image prep-build-test) yarn test:e2e:chrome:parallel"
    parallelism: 9
    # artifact_paths:
    #   - "test-artifacts"

  - key: "e2e-firefox"
    label: ":firefox: firefox e2e test %n"
    branches: "buildkite"
    depends_on: "prep-build-test"
    commands:
      - "docker run $(./.buildkite/scripts/target2image prep-build-test) yarn test:e2e:firefox:parallel"
    parallelism: 9
    # artifact_paths:
    #   - "test-artifacts"

  - key: "benchmark"
    label: ":chrome: benchmark"
    branches: "buildkite"
    depends_on: "prep-build-test"
    command: "docker run $(./.buildkite/scripts/target2image prep-build-test) yarn benchmark:chrome --out test-artifacts/chrome/benchmark/pageload.json"
    # artifact_paths:
    #   - "test-artifacts"

  - key: "test-mozilla-lint"
    label: ":firefox: mozilla lint"
    branches: "buildkite"
    depends_on: "prep-build"
    command: "docker run --env NODE_OPTIONS=--max_old_space_size=3072 $(./.buildkite/scripts/target2image prep-build) yarn mozilla-lint"
