steps:
  # L0
  - key: "base"
    label: "build base image"
    branches: "buildkite"
    command: "DOCKER_BUILDKIT=1 docker build --progress=plain --target=base -t portal-base-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT ."

  # # - wait

  ### L1
  - key: "audit-deps"
    label: "yarn audit"
    branches: "buildkite"
    depends_on: "base"
    command: "DOCKER_BUILDKIT=1 docker build --progress=plain --target=audit-deps -t portal-audit-deps-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT ."

  - key: "prep-deps"
    label: "install deps"
    branches: "buildkite"
    depends_on: "base"
    command: "DOCKER_BUILDKIT=1 docker build --progress=plain --target=prep-deps -t portal-prep-deps-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT ."

  - key: "shellcheck"
    label: "shellcheck"
    branches: "buildkite"
    depends_on: "prep-deps"
    command: "DOCKER_BUILDKIT=1 docker build --progress=plain --target=shellcheck -t portal-shellcheck-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT ."

  - key: "prep-deps-browser"
    label: "install deps with browsers"
    branches: "buildkite"
    depends_on: "prep-deps"
    command: "DOCKER_BUILDKIT=1 docker build --progress=plain --target=prep-deps-browser -t portal-prep-deps-browser-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT ."

  # - wait

  ### L2

  - key: "prep-build-storybook"
    label: "build storybook"
    branches: "buildkite"
    depends_on: "prep-deps"
    command: "docker run --rm portal-prep-deps-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT yarn storybook:build"

  - key: "prep-build"
    label: "yarn dist"
    branches: "buildkite"
    depends_on: "prep-deps"
    command: "DOCKER_BUILDKIT=1 docker build --progress=plain --target=prep-build -t portal-prep-build-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT ."
    # artifact_paths:
    #   - "builds"


  - key: "test-unit"
    label: "unit test"
    branches: "buildkite"
    depends_on: "prep-deps"
    command: "docker run --rm portal-prep-deps-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT yarn test:unit"
    # artifact_paths:
    #   - ".nyc_output"
    #   - "coverage"


  - key: "test-unit-global"
    label: "unit test global"
    branches: "buildkite"
    depends_on: "prep-deps"
    command: "docker run --rm portal-prep-deps-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT yarn test:unit:global"

  - key: "test-lint"
    label: "lint"
    branches: "buildkite"
    depends_on: "prep-deps"
    command:
      - "docker run --rm portal-prep-deps-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT yarn lint"
      - "docker run --rm portal-prep-deps-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT yarn verify-locales"

  - key: "test-lint-lockfile"
    label: "lint lockfile"
    branches: "buildkite"
    depends_on: "prep-deps"
    command: "docker run --rm portal-prep-deps-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT yarn lint:lockfile"

  - key: "prep-scss"
    label: "build scss"
    branches: "buildkite"
    depends_on: "prep-deps-browser"
    command: "DOCKER_BUILDKIT=1 docker build --progress=plain --target=prep-scss -t portal-prep-scss-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT ."

  - key: "prep-build-test"
    label: "build test"
    branches: "buildkite"
    depends_on: "prep-deps-browser"
    command: "DOCKER_BUILDKIT=1 docker build --progress=plain --target=prep-build-test -t portal-prep-build-test-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT ."
  # - wait

  ### Level 3
  - key: "test-flat-chrome"
    env:
      browsers: "'[\"Chrome\"]'"
    label: "chrome integration test"
    branches: "buildkite"
    depends_on: "prep-scss"
    command: "docker run --rm portal-prep-scss-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT"

  - key: "test-flat-firefox"
    env:
      browsers: "'[\"FireFox\"]'"
    label: "firefox integration test"
    branches: "buildkite"
    depends_on: "prep-scss"
    command: "docker run --rm portal-prep-scss-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT"

  - key: "e2e-chrome"
    label: "chrome e2e test %n"
    branches: "buildkite"
    depends_on: "prep-build-test"
    command: "docker run --rm portal-prep-build-test-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT yarn test:e2e:chrome"
    parallelism: 9
    # artifact_paths:
    #   - "test-artifacts"

  - key: "e2e-firefox"
    label: "firefox e2e test %n"
    branches: "buildkite"
    depends_on: "prep-build-test"
    command: "docker run --rm portal-prep-build-test-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT yarn test:e2e:firefox"
    parallelism: 9
    # artifact_paths:
    #   - "test-artifacts"

  - key: "benchmark"
    label: "benchmark"
    branches: "buildkite"
    depends_on: "prep-build-test"
    command: "docker run --rm portal-prep-build-test-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT yarn benchmark:chrome --out test-artifacts/chrome/benchmark/pageload.json"
    # artifact_paths:
    #   - "test-artifacts"

  - key: "test-mozilla-lint"
    label: "mozilla lint"
    branches: "buildkite"
    depends_on: "prep-build"
    command: "docker run --rm --env NODE_OPTIONS=--max_old_space_size=3072 portal-prep-build-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT yarn mozilla-lint"

  # - wait
