steps:
  # L1
  - key: "base"
    label: ":docker: build base image"
    branches: "buildkite"
    command: "BUILD_TARGET=base ./.buildkite/scripts/docker-build"

  # L2
  - key: "audit-deps"
    label: ":nsp: yarn audit"
    branches: "buildkite"
    depends_on: "base"
    command: "BUILD_TARGET=audit-deps ./.buildkite/scripts/docker-build"

  - key: "prep-deps"
    label: ":parcel: yarn install"
    branches: "buildkite"
    depends_on: "base"
    command: "BUILD_TARGET=prep-deps ./.buildkite/scripts/docker-build"

  # L3
  - key: "prep-deps-with-files"
    label: ":parcel: install deps with all files"
    branches: "buildkite"
    depends_on: "prep-deps"
    command: "BUILD_TARGET=prep-deps-with-files ./.buildkite/scripts/docker-build"

  - key: "prep-deps-with-prod-files"
    label: ":parcel: install deps with prod files"
    branches: "buildkite"
    depends_on: "prep-deps"
    command: "BUILD_TARGET=prep-deps-with-prod-files ./.buildkite/scripts/docker-build"

  - key: "test-lint-lockfile"
    label: ":nsp: lint lockfile"
    branches: "buildkite"
    depends_on: "prep-deps"
    command: "BUILD_TARGET=test-lint-lockfile ./.buildkite/scripts/docker-build"

  # L4
  - key: "prep-deps-browser"
    label: ":parcel: install deps with browsers"
    branches: "buildkite"
    depends_on: "prep-deps-with-files"
    command: "BUILD_TARGET=prep-deps-browser ./.buildkite/scripts/docker-build"

  - key: "prep-test"
    label: ":parcel: unit prep"
    branches: "buildkite"
    depends_on: "prep-deps-with-prod-files"
    command: "BUILD_TARGET=prep-test ./.buildkite/scripts/docker-build"

  - key: "prep-build"
    label: ":parcel: yarn dist"
    branches: "buildkite"
    depends_on: "prep-deps-with-prod-files"
    command: "BUILD_TARGET=prep-build ./.buildkite/scripts/docker-build"
    # artifact_paths:
    #   - "builds"

  - key: "prep-build-storybook"
    label: ":storybook: build storybook"
    branches: "buildkite"
    depends_on: "prep-deps-with-prod-files"
    commands:
      - "BUILD_TARGET=prep-build-storybook ./.buildkite/scripts/docker-build"

  - key: "shellcheck"
    label: ":heavy_check_mark: shellcheck"
    branches: "buildkite"
    depends_on: "prep-deps-with-files"
    command: "BUILD_TARGET=shellcheck ./.buildkite/scripts/docker-build"

  - key: "test-lint"
    label: ":eslint: lint"
    branches: "buildkite"
    depends_on: "prep-deps-with-files"
    command: "BUILD_TARGET=test-lint ./.buildkite/scripts/docker-build"

  # L5
  - key: "prep-build-test"
    label: ":parcel: build test"
    branches: "buildkite"
    depends_on: "prep-deps-browser"
    command: "BUILD_TARGET=prep-build-test ./.buildkite/scripts/docker-build"

  - key: "prep-test-flat"
    label: ":parcel: build test flat"
    branches: "buildkite"
    depends_on: "prep-deps-browser"
    command: "BUILD_TARGET=prep-test-flat ./.buildkite/scripts/docker-build"

  - key: "test-unit"
    label: ":mocha: unit test"
    branches: "buildkite"
    depends_on: "prep-test"
    command: "BUILD_TARGET=test-unit ./.buildkite/scripts/docker-build"
    # artifact_paths:
    #   - ".nyc_output"
    #   - "coverage"

  - key: "test-unit-global"
    label: ":mocha: unit test global"
    branches: "buildkite"
    depends_on: "prep-test"
    command: "BUILD_TARGET=test-unit-global ./.buildkite/scripts/docker-build"

  - key: "test-mozilla-lint"
    label: ":firefox: mozilla lint"
    branches: "buildkite"
    depends_on: "prep-build"
    command: "BUILD_TARGET=test-mozilla-lint ./.buildkite/scripts/docker-build"

  # L6
  - key: "test-flat-chrome"
    label: ":chrome: chrome integration test"
    branches: "buildkite"
    depends_on: "prep-test-flat"
    command: "BUILD_TARGET=test-flat ./.buildkite/scripts/docker-build --build-arg browsers='[\"Chrome\"]'"

  - key: "test-flat-firefox"
    label: ":firefox: firefox integration test"
    branches: "buildkite"
    depends_on: "prep-test-flat"
    command: "BUILD_TARGET=test-flat ./.buildkite/scripts/docker-build --build-arg browsers='[\"FireFox\"]'"

  - key: "e2e-chrome"
    label: ":chrome: chrome e2e test %n"
    branches: "buildkite"
    depends_on: "prep-build-test"
    commands:
      - "BUILD_TARGET=e2e-chrome ./.buildkite/scripts/docker-build"
    parallelism: 9
    # artifact_paths:
    #   - "test-artifacts"

  - key: "e2e-firefox"
    label: ":firefox: firefox e2e test %n"
    branches: "buildkite"
    depends_on: "prep-build-test"
    commands:
      - "BUILD_TARGET=e2e-firefox ./.buildkite/scripts/docker-build"
    parallelism: 9
    # artifact_paths:
    #   - "test-artifacts"

  - key: "benchmark"
    label: ":chrome: benchmark"
    branches: "buildkite"
    depends_on: "prep-build-test"
    command: "BUILD_TARGET=benchmark ./.buildkite/scripts/docker-build"
    # artifact_paths:
    #   - "test-artifacts"
