#!/usr/bin/env bash

set -x
set -e
set -o pipefail

export DOCKER_BUILDKIT=1
docker build \
       --progress=plain \
       --target=$BUILD_TARGET \
       --build-arg BUILDKITE="$BUILDKITE" \
       --build-arg BUILDKITE_ARTIFACT_PATHS="$BUILDKITE_ARTIFACT_PATHS" \
       --build-arg BUILDKITE_BRANCH="$BUILDKITE_BRANCH" \
       --build-arg BUILDKITE_COMMAND="$BUILDKITE_COMMAND" \
       --build-arg BUILDKITE_LABEL="$BUILDKITE_LABEL" \
       --build-arg BUILDKITE_ORGANIZATION_SLUG="$BUILDKITE_ORGANIZATION_SLUG" \
       --build-arg BUILDKITE_PARALLEL_JOB="$BUILDKITE_PARALLEL_JOB" \
       --build-arg BUILDKITE_PARALLEL_JOB_COUNT="$BUILDKITE_PARALLEL_JOB_COUNT" \
       --build-arg BUILDKITE_REPO="$BUILDKITE_REPO" \
       --build-arg CI="$CI" \
       -t portal-$BUILD_TARGET-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_COMMIT \
       $@ \
       .
